---
- hosts: all
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - server
    - vagrant_local
    - apache
    - mariadb
    - beanstalkd
    - php
    - php-phalcon2
    - xdebug
    - app
